# Generated by Django 4.1.7 on 2023-03-02 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stake',
            old_name='investor',
            new_name='investor_agent',
        ),
        migrations.AddField(
            model_name='stake',
            name='stake_user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
